Refactor permission checking middleware
byndcloud/quoti-auth pull request #3
Opened 2021-10-15 14:33 UTC by nmf2

Um refactor para desacoplar a lógica de checagem de permissão do middleware do express.

2021-10-22 12:38 UTC, ovictoraurelio requested changes

2021-10-22 12:38 UTC, ovictoraurelio commented on src/permissions.js
> +  return validators => {
Por que removeu a atribuição default de array vazio?

2021-10-26 15:55 UTC, nmf2 commented on src/permissions.js
> +  return validators => {
Bom ponto. Tá mais pra "não adicionar" do que "remover" (mas explicar não vale a pena)
```suggestion
  return (validators = []) => {
```

2021-10-27 04:15 UTC, nmf2 commented
@ovictoraurelio, pronto para review.

2021-11-02 16:25 UTC, nmf2 commented
@ovictoraurelio ?

2021-11-02 16:54 UTC, merged