Bugfix/expose-multi-org-permissions-getter
byndcloud/quoti-auth pull request #7
Opened 2022-01-10 15:55 UTC by nmf2

Expoe a função para busca de permissões para usuários de multiplas orgs e faz uma checagem do tipo das permissões passadas para o middleware de permissions.

2022-01-11 11:53 UTC, ovictoraurelio requested changes
<img src="https://media1.giphy.com/media/HxnMNAEQgHqEHcGKBb/giphy.gif"/>

2022-01-11 11:53 UTC, ovictoraurelio commented on src/permissions.js
> +      throw error
Tu criou uma variável **`validatorsOrFunctionType`** utiliza ela para compor a mensagem de Erro mas não utiliza ela na comparação do if. Ao invés disso, refaz a sentença de `typeof validatorsOrFunction`

2022-01-11 11:53 UTC, ovictoraurelio commented on src/permissions.js
> +      // try {
Remover comentário, por favor.

2022-01-11 11:53 UTC, ovictoraurelio commented on src/permissions.js
> +      // }
Remover comentários, por favor.

2022-01-12 20:58 UTC, nmf2 commented on src/permissions.js
> +      throw error
Done! Sorry :'(

2022-01-12 20:58 UTC, nmf2 commented on src/permissions.js
> +      // try {
Done! Sorry :'(

2022-01-12 20:58 UTC, nmf2 commented on src/permissions.js
> +      // }
Done! Sorry :'(

2022-01-12 21:30 UTC, ovictoraurelio approved these changes
<img src="https://media3.giphy.com/media/3Hb1STCbFroaErsYT0/giphy.gif"/>

2022-01-12 21:32 UTC, merged